openapi: 3.0.3
info:
  title: Library API
  version: 1.6.0
  description: STD21089
servers:
  - url: https://library.com
tags:
  - name: Books
  - name: Authors
  - name: Topics
paths:
  /books:
    get:
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      tags:
        - Books
      parameters:
        - $ref: '#/components/parameters/QueryPagination'
      responses:
        200:
          description: The list of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        400:
          $ref: '#/components/schemas/ApiResponse'
        403:
          $ref: '#/components/schemas/ApiResponse'
        500:
          $ref: '#/components/schemas/ApiResponse'
    put:
      summary: Create or update a list of books
      operationId: crupdateBooks
      tags:
        - Books
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CrupdateBook'
      responses:
        200:
          description: The list of created or updated books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        400:
          $ref: '#/components/schemas/ApiResponse'
        403:
          $ref: '#/components/schemas/ApiResponse'
        500:
          $ref: '#/components/schemas/ApiResponse'
        
  /books/{bookId}:
    get:
      summary: Get a specific book
      description: Get a specific book by its ID
      operationId: getBookById
      tags:
        - Books
      parameters:
        - in: path
          name: bookId
          description: ID of the book to return
          required: true
          schema:
            type: string
      responses:
        200:
          description: The requested book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        400:
          $ref: '#/components/schemas/ApiResponse'
        403:
          $ref: '#/components/schemas/ApiResponse'
        500:
          $ref: '#/components/schemas/ApiResponse'
  /authors:
    get:
      summary: Get all authors
      description: Get all authors or filter by name
      operationId: getAuthors
      tags:
        - Authors
      parameters:
        - $ref: '#/components/parameters/QueryPagination'
      responses:
        200:
          description: The list of filtered authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
        400:
          $ref: '#/components/schemas/ApiResponse'
        403:
          $ref: '#/components/schemas/ApiResponse'
        500:
          $ref: '#/components/schemas/ApiResponse'
  /authorsTopics:
    get:
      summary: Get list of AuthorTopics
      description: Return a list of AuthorTopics
      operationId: getAuthorsTopics
      tags:
        - Authors
      parameters:
        - in: query
          name: authorId
          description: ID of the author (optional)
          required: false
          schema:
            type: string
      responses:
        200:
          description: The list of AuthorTopics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AuthorTopic'
        400:
          $ref: '#/components/schemas/ApiResponse'
        403:
          $ref: '#/components/schemas/ApiResponse'
        500:
          $ref: '#/components/schemas/ApiResponse'
  /author/page/{page}/size/{size}:
    get:
      summary: get page size
      tags:
        - Authors
      operationId: getPageSize
      parameters:
          - name: page
            in: path
            required: true
            schema:
              type: string
      responses:
        200:
          description: The list of AuthorTopics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/parameters/Page'
        400:
          $ref: '#/components/schemas/ApiResponse'
        403:
          $ref: '#/components/schemas/ApiResponse'
        500:
          $ref: '#/components/schemas/ApiResponse'
  /authors/import:
    post:
      summary: Import authors
      operationId: importAuthors
      tags:
        - Authors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Author'
      responses:
        200:
          description: The list of imported authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
        400:
          $ref: '#/components/schemas/ApiResponse'
        403:
          $ref: '#/components/schemas/ApiResponse'
        500:
          $ref: '#/components/schemas/ApiResponse'
    put:
      summary: Create or update an author
      operationId: crupdateAuthor
      tags:
        - Authors
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        200:
          description: The created or updated author
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        400:
          $ref: '#/components/schemas/ApiResponse'
        403:
          $ref: '#/components/schemas/ApiResponse'
        500:
          $ref: '#/components/schemas/ApiResponse'
    delete:
      summary: Delete an author
      operationId: deleteAuthor
      tags:
        - Authors
      parameters:
        - in: query
          name: authorId
          description: ID of the author to be deleted
          required: true
          schema:
            type: string
      responses:
        200:
          description: The author has been successfully deleted
        400:
          $ref: '#/components/schemas/ApiResponse'
        403:
          $ref: '#/components/schemas/ApiResponse'
        500:
          $ref: '#/components/schemas/ApiResponse'
  /books/{bookId}/authors/{authorId}:
    put:
      tags:
        - Books
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: string
        - name: authorId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: The author has been successfully modified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        400:
          $ref: '#/components/schemas/ApiResponse'
        403:
          $ref: '#/components/schemas/ApiResponse'
        500:
          $ref: '#/components/schemas/ApiResponse'
  /topics:
    get:
      summary: Get all topics
      description: Get all available topics
      tags:
        - Topics
      operationId: getTopic
      parameters:
        - $ref: '#/components/parameters/QueryPagination'
      responses:
        200:
          description: The list of filtered topics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topic'
        400:
          $ref: '#/components/schemas/ApiResponse'
        403:
          $ref: '#/components/schemas/ApiResponse'
        500:
          $ref: '#/components/schemas/ApiResponse'
    put:
      summary: Create or update a topic
      operationId: crupdateTopic
      tags:
        - Topics
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Topic'
      responses:
        200:
          description: The created or updated topic
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Topic'
        400:
          $ref: '#/components/schemas/ApiResponse'
        403:
          $ref: '#/components/schemas/ApiResponse'
        500:
          $ref: '#/components/schemas/ApiResponse'
    delete:
      summary: Delete a topic
      operationId: deleteTopic
      tags:
        - Topics
      parameters:
        - in: query
          name: topicId
          description: ID of the topic to be deleted
          required: true
          schema:
            type: string
      responses:
        200:
          description: The topic has been successfully deleted
        400:
          $ref: '#/components/schemas/ApiResponse'
        403:
          $ref: '#/components/schemas/ApiResponse'
        500:
          $ref: '#/components/schemas/ApiResponse'
  /books/{bookId}/topics/{topicId}:
    put:
      tags:
        - Books
      parameters:
        - in: path
          name: bookId
          required: true
          schema:
            type: string
        - in: path
          name: topicId
          required: true
          schema:
            type: string
      responses:
        200:
          description: The author has been successfully modified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        400:
          $ref: '#/components/schemas/ApiResponse'
        403:
          $ref: '#/components/schemas/ApiResponse'
        500:
          $ref: '#/components/schemas/ApiResponse'
  /books/topics:
    put:
      tags:
        - Books
      summary: Update a list of book's topics
      operationId: updateBooksTopics
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      responses:
        200:
          description: The list of books' topics has been successfully modified
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        400:
          $ref: '#/components/schemas/ApiResponse'
        403:
          $ref: '#/components/schemas/ApiResponse'
        500:
          $ref: '#/components/schemas/ApiResponse'
  /books/import:
    post:
      summary: Import books
      operationId: importBooks
      tags:
        - Books
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      responses:
        200:
          description: The list of imported books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        400:
          $ref: '#/components/schemas/ApiResponse'
        403:
          $ref: '#/components/schemas/ApiResponse'
        500:
          $ref: '#/components/schemas/ApiResponse'
components:
  schemas:
    Sex:
      type: string
      enum:
        - M
        - F
    Author:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrupdateBook'
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          $ref: '#/components/schemas/Sex'
    Book:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrupdateBook'
      properties:
        author:
          $ref: '#/components/schemas/Author'
        topic:
          $ref: '#/components/schemas/Topic'
    CrupdateBook:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        pageNumbers:
          type: integer
        releaseDate:
          type: string
          format: date
    Topic:
      properties:
        topicName:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
    AuthorTopic:
      type: object
      properties:
        authorId:
          type: string
        authorName:
          type: string
        authorSex:
          $ref: '#/components/schemas/Sex'
        topics:
          type: array
          items:
            $ref: '#/components/schemas/Topic'
    ImportAuthor:
      oneOf:
        - type: string
          format: binary
          description: Excel file for author import
        - type: array
          items:
            type: object
            properties:
              authorName:
                type: string
              sex:
                $ref: '#/components/schemas/Sex'
      discriminator:
          propertyName: importType
          mapping:
            excel: '#/components/schemas/ImportAuthorExcel'
            json: '#/components/schemas/ImportAuthorJSON'
    ImportAuthorExcel:
      type: string
      format: binary
      description: Excel file for author import

    ImportAuthorJSON:
      type: array
      items:
        type: object
        properties:
          authorName:
            type: string
          sex:
            $ref: '#/components/schemas/Sex'
    ImportBook:
      oneOf:
        - type: string
          format: binary
          description: Excel file for book import
        - type: array
          items:
            type: object
            properties:
              bookName:
                type: string
              author:
                $ref: '#/components/schemas/Author'
              pageNumbers:
                type: integer
              topic:
                $ref: '#/components/schemas/Topic'
              releaseDate:
                type: string
                format: date
              idAuthor:
                type: string
      discriminator:
        propertyName: importType
        mapping:
          excel: '#/components/schemas/ImportBookExcel'
          json: '#/components/schemas/ImportBookJSON'
    ImportBookExcel:
      type: string
      format: binary
      description: Excel file for book import
    ImportBookJSON:
      type: array
      items:
        type: object
        properties:
          bookName:
            type: string
          author:
            $ref: '#/components/schemas/Author'
          pageNumbers:
            type: integer
          topic:
            $ref: '#/components/schemas/Topic'
          releaseDate:
            type: string
            format: date
          idAuthor:
            type: string
    ApiResponse:
      type: object
      properties:
        status:
          type: object
          properties:
            code:
              type: integer
              format: int32
            message:
              type: string
        body:
          type: object
  responses:
    400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'

    403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'

    500:
      description: Internal server error occurred
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'

  parameters:
    Page:
      name: page
      description: Page Number for pagination (default 1)
      in: query
      schema:
        type: integer
        default: 1
      required: false
    PageSize:
      name: pageSize
      description: Page size for pagination default 50
      in: query
      schema:
        type: integer
        default: 50
      required: false
    Page1:
      name: page
      description: Page Number for pagination (default 1)
      in: path
      schema:
        type: integer
        default: 1
      required: true
    PageSize1:
      name: pageSize
      description: Page size for pagination default 50
      in: path
      schema:
        type: integer
        default: 50
      required: true
    QueryPagination:
      in: query
      name: queryPagination
      schema:
        allOf: 
          - $ref: '#/components/parameters/Page'
    PathPagination:
      in: path
      name: pathPagination
      required: true
      schema:
        allOf: 
          - $ref: '#/components/parameters/Page'
          - $ref: '#/components/parameters/PageSize'
